--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Diduhless/Reports
build-by-default: true
projects:
  Reports:
    path: ""
    icon: "icon.png"
    libs:
      - src: andresbytes/EasyUI/libEasyUI
        version: 1.0.2
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: 1.0.2
...